"""empty message

Revision ID: 76e631020a1d
Revises: dc9539f26234
Create Date: 2021-02-09 11:46:36.502240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76e631020a1d'
down_revision = 'dc9539f26234'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'routes', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'routes', type_='foreignkey')
    # ### end Alembic commands ###
